import type { schema } from "@workspace/ui/components/data-table"
import { z } from "zod"

export const dataTableDemoRows: z.infer<typeof schema>[] = [
  {
    id: 1,
    header: "Customer import QA",
    type: "Checklist",
    status: "In Process",
    target: "32",
    limit: "8",
    reviewer: "Anita Chen",
  },
  {
    id: 2,
    header: "Regional rollout brief",
    type: "Narrative",
    status: "Done",
    target: "14",
    limit: "12",
    reviewer: "Marcus Li",
  },
  {
    id: 3,
    header: "Store access matrix",
    type: "Access Matrix",
    status: "Done",
    target: "18",
    limit: "10",
    reviewer: "Anita Chen",
  },
  {
    id: 4,
    header: "Promotion audit sample",
    type: "Audit Pack",
    status: "In Process",
    target: "26",
    limit: "16",
    reviewer: "Assign reviewer",
  },
  {
    id: 5,
    header: "POS exception summary",
    type: "Summary",
    status: "Done",
    target: "9",
    limit: "6",
    reviewer: "Leo Park",
  },
  {
    id: 6,
    header: "Warehouse sync checklist",
    type: "Checklist",
    status: "In Process",
    target: "20",
    limit: "7",
    reviewer: "Marcus Li",
  },
  {
    id: 7,
    header: "Refund policy comparison",
    type: "Analysis",
    status: "Done",
    target: "11",
    limit: "9",
    reviewer: "Leo Park",
  },
  {
    id: 8,
    header: "Role permission delta",
    type: "Access Matrix",
    status: "In Process",
    target: "17",
    limit: "5",
    reviewer: "Assign reviewer",
  },
  {
    id: 9,
    header: "Holiday staffing plan",
    type: "Plan",
    status: "Done",
    target: "22",
    limit: "14",
    reviewer: "Anita Chen",
  },
  {
    id: 10,
    header: "Vendor onboarding packet",
    type: "Packet",
    status: "In Process",
    target: "28",
    limit: "11",
    reviewer: "Leo Park",
  },
  {
    id: 11,
    header: "Flagship launch script",
    type: "Runbook",
    status: "Done",
    target: "16",
    limit: "8",
    reviewer: "Marcus Li",
  },
  {
    id: 12,
    header: "Daily exception digest",
    type: "Summary",
    status: "In Process",
    target: "13",
    limit: "4",
    reviewer: "Assign reviewer",
  },
]
